### PR TITLE
Switch CI to use GitHub Actions

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by cdwensley** [comment]
Obviously I realise that this PR is part of the global change of testing procedures in GAP, but that the details of what is being done mean nothing to me. 
Are you waiting for me to "Merge pull request" or is the PR not yet complete? 
Can I help with updating the other Bangor packages or should I just wait for others to do this?

**Comment by fingolfin** [comment]
@cdwensley I have a script that let's me submit a similar PR to repository with a few keystrokes; the main work is to "adjust" the `.github/workflows/CI.yml` to run the desired tests, install prerequisites etc. So if you tell me which packages you'd like to be upgraded, I'll be happy to assist. Alternatively, you are of course also welcome to do it yourself, based on this PR, and of course "we" (well, me, but probably other people in the GAP slack) will be happy to help and answer questions.

You could simply merge this, but I wanted to give you a chance to look at it, and ask questions if you have any.

**Comment by cdwensley** [comment]
As far as I can see there is nothing in .github/workflows/CI.yml that is specific to Utils (or any other package).  The only entry specific to Utils is the header in README.md.  So I am happy to merge this PR and will think about the other packages once a non-GAP deadline I'm working towards has past.

**Comment by fingolfin** [comment]
The "specific" bits are which GAP versions to test (eg if a package requires GAP 4.10'then don't test 4.9), whether to test 32bit GAP builds (in general only useful if there is a kernel extension) and perhaps prerequisites -- but that's all the same as for Travis, only the concrete way to do it changed

**Comment by cdwensley** [comment]
This does not belong here, but is a quick way of contacting @fingolfin. 
I've not touched Utils since last summer and now find the following: 
Christopher-Wensleys-iMac:utils christopherwensley$ git status
On branch master
Your branch is up to date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	doc/_AutoDocMainFile.xml
	doc/_Chunks.xml
	doc/bib.xml.bib
	doc/title.xml
	doc/utils.xml
	setup-gh-pages
nothing added to commit but untracked files present (use "git add" to track)

Can you remind me on which of these "git add" should be used, and which added to .gitignore?

**Comment by fingolfin** [comment]
The setup script can be deleted, the rest added to .gitignore

**Pull request merged**
