### PR TITLE
moved download.tst back to tst/ from tst-spec/

### PR DESCRIPTION
**Pull request by cdwensley**
This follows the changes by @fingolfin to init.g and read.g in PR #55.

### CODE REVIEW

**Comment by cdwensley** [comment]
@ThomasBreuer - can you review this please, as I cannot remember why we put download.tst into a separate test folder, so have put it back into tst/. 
@angeldelriomateos - sorry, did not intend to ask for a review from you, and cannot find how to remove you from the list of reviewers.

**Comment by ThomasBreuer** [comment]
As far as I see, `download.tst` has been moved from `tst` to `tst-spec` in pull request #52.
Concerning the question why the file has been moved away from `tst`, my understanding is that one wanted to leave out this file from the `TestDirectory` call that runs over all testfiles in `tst`, in order to run `download.tst` only in GAP 4.12 but not in GAP 4.13.

The proposed changes are fine from my point of view. If GAP 4.13 will contain some code that makes `download.tst` obsolete then presumably other changes will be needed in the utils package, and then adjusting `download.tst` will be part of these changes.

(I do not have the permissions to assign myself as a reviewer, or to approve the pull request.)

**Comment by cdwensley** [comment]
@ThomasBreuer - thanks for your comments - I will merge this PR. 
It's very odd that you do not have permissions.  When I go to the 'Reviewers' marker on the right I get a list of 68 potential reviewers, but you are not included.  If I type '@ThomasBreuer' in the box, nothing happens. 
I've still got an awful lot to learn about GitHub!

**Comment by cdwensley** [comment]
This PR now part of the utils-0.78 release of 17/11/22.

**Pull request merged**
